import { Request, Response, NextFunction } from "express";
import * as aiService from "./ai-agent.service";
import { AiChatSchema, AiDraftReplySchema, AiReportSchema } from "./ai-agent.schema";
import { sendSuccess, sendError } from "../../utils/response";

// ─── POST /api/v1/ai-agent/chat ───────────────────────────────────────────────
export const copilotChat = async (req: Request, res: Response, next: NextFunction) => {
  try {
    const parsed = AiChatSchema.safeParse(req.body);
    if (!parsed.success) {
      sendError(res, { code: "VALIDATION_ERROR", message: parsed.error.errors[0]?.message ?? "Invalid input" }, 400);
      return;
    }
    const result = await aiService.adminCopilotChat(parsed.data);
    sendSuccess(res, result, "AI Copilot response generated", 200);
  } catch (error: any) {
    next(error);
  }
};

// ─── POST /api/v1/ai-agent/draft-reply ───────────────────────────────────────
export const draftReply = async (req: Request, res: Response, next: NextFunction) => {
  try {
    const parsed = AiDraftReplySchema.safeParse(req.body);
    if (!parsed.success) {
      sendError(res, { code: "VALIDATION_ERROR", message: parsed.error.errors[0]?.message ?? "Invalid input" }, 400);
      return;
    }
    const result = await aiService.draftPoEmailReply(parsed.data);
    sendSuccess(res, result, "Email reply drafted by AI", 200);
  } catch (error: any) {
    next(error);
  }
};

// ─── POST /api/v1/ai-agent/report ────────────────────────────────────────────
export const generateReport = async (req: Request, res: Response, next: NextFunction) => {
  try {
    const parsed = AiReportSchema.safeParse(req.body);
    if (!parsed.success) {
      sendError(res, { code: "VALIDATION_ERROR", message: parsed.error.errors[0]?.message ?? "Invalid input" }, 400);
      return;
    }
    const result = await aiService.generateBusinessReport(parsed.data);
    sendSuccess(res, result, "Business report generated by AI", 200);
  } catch (error: any) {
    next(error);
  }
};
